"""x402 spend ledger — stateless USDC Transfer scan on Base.

Reconstructs a wallet's x402 payment history from chain data at request
time. No stored state: the service registry is a versioned JSON bundled
with the deploy (data/x402_registry.json, regenerated by
scripts/build-registry.mjs), and report jobs use the existing DDB job
store + an S3 bucket for the rendered files.

Identification heuristic, in priority order:
  a. Transfer counterparty matches a registry recipient -> labeled x402.
  b. Tx calldata starts with an EIP-3009 selector -> x402, unidentified
     service. First-4-bytes match only: the CDP facilitator submits from
     a rotating relayer pool (11 unique senders across 12 sampled
     settlements, so no stable address list exists) and appends an
     ERC-8021 builder-code suffix that breaks strict ABI decoding.
  c. Everything else -> excluded unless include_unfiltered.

Base block timestamps are exactly GENESIS_TS + 2n (verified zero drift
across blocks 0..48.6M), so date->block mapping and per-transfer
timestamps are pure arithmetic — no extra RPC. The invariant is
re-checked against the chain tip on every scan.
"""

from __future__ import annotations

import csv
import hashlib
import io
import json
import logging
import os
import time
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import Any

log = logging.getLogger("ledger")

SPEC_VERSION = "1.0"
GENESIS_TS = 1686789347  # Base mainnet block 0
BLOCK_TIME = 2
USDC_BASE = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
TRANSFER_TOPIC = "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"
# EIP-3009 on FiatTokenV2_2 (impl 0x2ce6...d779): transferWithAuthorization
# (v,r,s) / (bytes), receiveWithAuthorization (v,r,s) / (bytes).
EIP3009_SELECTORS = {"e3ee160e", "cf092995", "ef55bec6", "88b7ab63"}

MAX_LOGS = 25_000          # spec hard cap per request
MAX_TX_INSPECTIONS = 5_000  # calldata lookups for registry-unmatched transfers
# mainnet.base.org caps eth_getLogs at 10k blocks (413 above that) and serves
# a 10k chunk in ~0.4s, but rate-limits sustained concurrency (429s at 20).
CHUNK_BLOCKS = 10_000
MIN_CHUNK_BLOCKS = 1_000
SCAN_WORKERS = 10
RETRY_BACKOFF_S = 0.5  # doubled per attempt, 5 attempts
INSPECT_WORKERS = 10
MAX_RANGE_DAYS = 366
DAILY_CAP = 90  # beyond this many days, roll daily series up to weeks

BASE_RPC_URL = os.getenv("BASE_RPC_URL", "https://mainnet.base.org")

_REGISTRY_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "x402_registry.json")


class LedgerError(Exception):
    """Machine-readable request failure: {"error": code, "message": human}."""

    def __init__(self, code: str, message: str, status: int = 400, **extra: Any):
        super().__init__(message)
        self.code = code
        self.message = message
        self.status = status
        self.extra = extra

    def body(self) -> dict[str, Any]:
        return {"error": self.code, "message": self.message, **self.extra}


# --- registry ----------------------------------------------------------------

_registry_cache: dict[str, Any] | None = None


def registry() -> dict[str, Any]:
    global _registry_cache
    if _registry_cache is None:
        with open(_REGISTRY_PATH) as f:
            data = json.load(f)
        recipients: dict[str, dict[str, Any]] = {}
        # services are sorted by service_id in the file; first writer wins so
        # a recipient shared across services resolves deterministically.
        for svc in data["services"]:
            for addr in svc["recipients"]:
                recipients.setdefault(addr.lower(), svc)
        _registry_cache = {
            "version": data["registry_version"],
            "recipients": recipients,
        }
    return _registry_cache


# --- chain access ------------------------------------------------------------

def _w3():
    from web3 import Web3
    return Web3(Web3.HTTPProvider(BASE_RPC_URL, request_kwargs={"timeout": 25}))


def _ts_of(block: int) -> int:
    return GENESIS_TS + BLOCK_TIME * block


def _block_at(ts: int, latest: int) -> int:
    return max(0, min(latest, (ts - GENESIS_TS) // BLOCK_TIME))


def _iso(ts: int) -> str:
    return datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _get_logs(w3, frm: int, to: int, topics: list, attempt: int = 0) -> list:
    """eth_getLogs with two failure paths: rate limits (429/timeout) back off
    and retry the same range; range rejections (413 etc.) bisect."""
    try:
        return w3.eth.get_logs({
            "address": USDC_BASE,
            "fromBlock": frm,
            "toBlock": to,
            "topics": topics,
        })
    except Exception as e:  # noqa: BLE001
        msg = str(e)
        if "429" in msg or "Too Many Requests" in msg or "timed out" in msg:
            if attempt >= 5:
                raise LedgerError("rpc_unavailable", "Base RPC rate limit persisted through retries", status=502)
            time.sleep(RETRY_BACKOFF_S * 2**attempt)
            return _get_logs(w3, frm, to, topics, attempt + 1)
        if to - frm < MIN_CHUNK_BLOCKS:
            raise LedgerError(
                "rpc_unavailable",
                f"Base RPC rejected a {to - frm}-block log query: {type(e).__name__}",
                status=502,
            )
        mid = (frm + to) // 2
        return _get_logs(w3, frm, mid, topics) + _get_logs(w3, mid + 1, to, topics)


def _wallet_topic(wallet: str) -> str:
    return "0x" + wallet[2:].lower().rjust(64, "0")


# --- request parsing ---------------------------------------------------------

def parse_range(from_s: str | None, to_s: str | None) -> tuple[int, int]:
    """ISO date or datetime -> (from_ts, to_ts) unix. Date-only 'from' means
    start of day, date-only 'to' means end of day; defaults: to=now,
    from=to-30d. Clamped to now."""
    now = int(time.time())

    def parse(s: str, end_of_day: bool) -> int:
        try:
            if len(s) == 10:
                dt = datetime.strptime(s, "%Y-%m-%d").replace(tzinfo=timezone.utc)
                if end_of_day:
                    dt += timedelta(days=1, seconds=-1)
            else:
                dt = datetime.fromisoformat(s.replace("Z", "+00:00"))
            return int(dt.timestamp())
        except ValueError:
            raise LedgerError("invalid_range", f"unparseable date: {s!r}")

    to_ts = min(parse(to_s, end_of_day=True), now) if to_s else now
    from_ts = parse(from_s, end_of_day=False) if from_s else to_ts - 30 * 86400
    if from_ts >= to_ts:
        raise LedgerError("invalid_range", "'from' must be before 'to'")
    if to_ts - from_ts > MAX_RANGE_DAYS * 86400:
        raise LedgerError("range_too_long", f"range exceeds {MAX_RANGE_DAYS} days")
    return from_ts, to_ts


def validate_wallet(wallet: str) -> str:
    if not isinstance(wallet, str) or len(wallet) != 42 or not wallet.startswith("0x"):
        raise LedgerError("invalid_wallet", "wallet must be a 0x-prefixed EVM address")
    try:
        int(wallet[2:], 16)
    except ValueError:
        raise LedgerError("invalid_wallet", "wallet must be a 0x-prefixed EVM address")
    return wallet.lower()


# --- scan --------------------------------------------------------------------

def scan(
    wallet: str,
    from_ts: int,
    to_ts: int,
    direction: str = "outbound",
    min_amount: str | None = None,
    include_unfiltered: bool = False,
    max_inspections: int = MAX_TX_INSPECTIONS,
) -> dict[str, Any]:
    """Returns {"transfers": [...], "registry_version": str}. Each transfer:
    ts, iso, tx_hash, log_index, counterparty, atomic, direction, service
    (registry row or None), category ("x402"|"other_transfer")."""
    reg = registry()
    w3 = _w3()

    try:
        tip = w3.eth.get_block("latest")
    except Exception as e:  # noqa: BLE001
        raise LedgerError("rpc_unavailable", f"Base RPC unreachable: {type(e).__name__}", status=502)
    if tip["timestamp"] != _ts_of(tip["number"]):
        raise LedgerError(
            "rpc_unavailable",
            "Base block-time invariant violated (chain params changed?) — refusing to mis-timestamp",
            status=502,
        )

    from_block = _block_at(from_ts, tip["number"])
    to_block = _block_at(to_ts, tip["number"])

    min_atomic = 0
    if min_amount is not None:
        try:
            min_atomic = int(Decimal(str(min_amount)) * 10**6)
        except Exception:  # noqa: BLE001
            raise LedgerError("invalid_range", f"unparseable min_amount: {min_amount!r}")

    directions = ["outbound", "inbound"] if direction == "both" else [direction]
    chunks: list[tuple[int, int, str]] = []
    for d in directions:
        b = from_block
        while b <= to_block:
            chunks.append((b, min(b + CHUNK_BLOCKS - 1, to_block), d))
            b += CHUNK_BLOCKS

    def fetch(chunk: tuple[int, int, str]) -> tuple[str, list]:
        frm, to, d = chunk
        topics = [TRANSFER_TOPIC]
        topics += [_wallet_topic(wallet)] if d == "outbound" else [None, _wallet_topic(wallet)]
        return d, _get_logs(w3, frm, to, topics)

    seen: set[tuple[str, int]] = set()
    transfers: list[dict[str, Any]] = []
    with ThreadPoolExecutor(max_workers=SCAN_WORKERS) as pool:
        for d, logs in pool.map(fetch, chunks):
            for lg in logs:
                tx_hash = lg["transactionHash"].hex()
                if not tx_hash.startswith("0x"):
                    tx_hash = "0x" + tx_hash
                key = (tx_hash, lg["logIndex"])
                if key in seen:  # wallet->wallet self-transfer under "both"
                    continue
                seen.add(key)
                atomic = int(lg["data"].hex(), 16)
                if atomic < min_atomic:
                    continue
                counterparty = "0x" + lg["topics"][2 if d == "outbound" else 1].hex()[-40:]
                transfers.append({
                    "ts": _ts_of(lg["blockNumber"]),
                    "tx_hash": tx_hash,
                    "log_index": lg["logIndex"],
                    "counterparty": counterparty.lower(),
                    "atomic": atomic,
                    "direction": d,
                })
            if len(transfers) > MAX_LOGS:
                raise LedgerError(
                    "range_too_active",
                    f"more than {MAX_LOGS} transfers in range",
                    status=422,
                    suggestion="narrow the date range",
                )

    # heuristic (a): registry match
    unmatched_txs: dict[str, None] = {}
    for t in transfers:
        svc = reg["recipients"].get(t["counterparty"])
        t["service"] = svc
        if svc is None:
            unmatched_txs[t["tx_hash"]] = None

    # heuristic (b): EIP-3009 selector on registry-unmatched transfers
    if len(unmatched_txs) > max_inspections:
        raise LedgerError(
            "range_too_active",
            f"more than {max_inspections} unidentified transactions to inspect in range",
            status=422,
            suggestion="narrow the date range or raise min_amount",
        )

    selector_is_3009: dict[str, bool] = {}
    if unmatched_txs:
        def inspect(tx_hash: str) -> tuple[str, bool]:
            try:
                tx = w3.eth.get_transaction(tx_hash)
                return tx_hash, bytes(tx["input"])[:4].hex() in EIP3009_SELECTORS
            except Exception:  # noqa: BLE001
                return tx_hash, False
        with ThreadPoolExecutor(max_workers=INSPECT_WORKERS) as pool:
            selector_is_3009 = dict(pool.map(inspect, unmatched_txs))

    out: list[dict[str, Any]] = []
    for t in transfers:
        if t["service"] is not None:
            t["category"] = "x402"
        elif selector_is_3009.get(t["tx_hash"]):
            t["category"] = "x402"
        elif include_unfiltered:
            t["category"] = "other_transfer"
        else:
            continue
        out.append(t)

    out.sort(key=lambda t: (t["ts"], t["tx_hash"], t["log_index"]))
    return {"transfers": out, "registry_version": reg["version"]}


# --- aggregation -------------------------------------------------------------

def _usdc(atomic: int) -> str:
    return f"{Decimal(atomic) / 10**6:.4f}"


def _usdc6(atomic: int) -> str:
    return f"{Decimal(atomic) / 10**6:.6f}"


def _group_label(t: dict[str, Any]) -> str:
    if t["service"]:
        return t["service"]["name"]
    return "Unknown recipient" if t["category"] == "x402" else "Other transfer"


def summarize(
    scanned: dict[str, Any],
    wallet: str,
    from_ts: int,
    to_ts: int,
    direction: str,
    group_by: str = "service",
) -> dict[str, Any]:
    transfers = scanned["transfers"]
    total_atomic = sum(t["atomic"] for t in transfers)
    identified_atomic = sum(t["atomic"] for t in transfers if t["service"])

    def day_of(t: dict[str, Any]) -> str:
        return datetime.fromtimestamp(t["ts"], tz=timezone.utc).strftime("%Y-%m-%d")

    def group_key(t: dict[str, Any]) -> tuple:
        if group_by == "recipient":
            k: tuple = (t["counterparty"],)
        elif group_by == "day":
            k = (day_of(t),)
        else:  # service: identified by service_id, unknowns by recipient
            k = (t["service"]["service_id"],) if t["service"] else (t["category"], t["counterparty"])
        return k + ((t["direction"],) if direction == "both" else ())

    groups: dict[tuple, list[dict[str, Any]]] = {}
    for t in transfers:
        groups.setdefault(group_key(t), []).append(t)

    group_rows = []
    for members in groups.values():
        atomic = sum(m["atomic"] for m in members)
        first = members[0]
        row: dict[str, Any] = {
            "label": day_of(first) if group_by == "day" else _group_label(first),
            "recipient": min(m["counterparty"] for m in members),
            "service_id": first["service"]["service_id"] if first["service"] else None,
            "usdc": _usdc(atomic),
            "tx_count": len(members),
            "avg_call_price": _usdc(atomic // len(members)),
            "first_tx": _iso(min(m["ts"] for m in members)),
            "last_tx": _iso(max(m["ts"] for m in members)),
        }
        if direction == "both":
            row["direction"] = first["direction"]
        group_rows.append(row)
    group_rows.sort(key=lambda r: (-Decimal(r["usdc"]), r["label"], r["recipient"]))

    daily: dict[str, dict[str, int]] = {}
    weekly = (to_ts - from_ts) > DAILY_CAP * 86400
    for t in transfers:
        d = datetime.fromtimestamp(t["ts"], tz=timezone.utc)
        if weekly:
            d -= timedelta(days=d.weekday())  # ISO week -> Monday
        bucket = daily.setdefault(d.strftime("%Y-%m-%d"), {"atomic": 0, "tx_count": 0})
        bucket["atomic"] += t["atomic"]
        bucket["tx_count"] += 1

    result: dict[str, Any] = {
        "wallet": wallet,
        "chain": "base",
        "range": {"from": _iso(from_ts), "to": _iso(to_ts)},
        "direction": direction,
        "totals": {
            "usdc": _usdc(total_atomic),
            "tx_count": len(transfers),
            "unique_recipients": len({t["counterparty"] for t in transfers}),
            "identified_pct": round(float(identified_atomic / total_atomic * 100), 1) if total_atomic else 0.0,
        },
        "groups": group_rows,
        "daily": [
            {"date": day, "usdc": _usdc(v["atomic"]), "tx_count": v["tx_count"]}
            for day, v in sorted(daily.items())
        ],
        "granularity": "week" if weekly else "day",
        "registry_version": scanned["registry_version"],
        "spec_version": SPEC_VERSION,
    }
    if direction == "both":
        result["totals"]["usdc_outbound"] = _usdc(sum(t["atomic"] for t in transfers if t["direction"] == "outbound"))
        result["totals"]["usdc_inbound"] = _usdc(sum(t["atomic"] for t in transfers if t["direction"] == "inbound"))
    return result


# --- report rendering (deterministic: no wall-clock anywhere) -----------------

_METHODOLOGY = """\
## Methodology

Transfers were identified as x402 payments by (a) matching the counterparty
against the anchor-x402 service registry (version {registry_version}), or
(b) the transaction calldata beginning with an EIP-3009 selector
(transferWithAuthorization / receiveWithAuthorization), the settlement
primitive of the x402 protocol. The selector check matches the first four
bytes of calldata only; payments routed through smart-account wrappers may
be missed. Registry coverage is reported as identified %. This is raw
accounting data, not tax categorization or financial advice.

JSON summary amounts are quantized to 4 decimal places; the CSV carries
exact 6-decimal USDC amounts and its SHA-256 is listed above, making the
markdown the single canonical artifact.

To verify this report: SHA-256 this file and compare the digest to the
32-byte payload embedded in the Base and Solana transactions linked in the
delivery envelope. The files are retrievable for 12 months; the on-chain
anchor proof is permanent.
"""


def render_report(
    scanned: dict[str, Any],
    summary: dict[str, Any],
    title: str | None = None,
    prepared_for: str | None = None,
) -> tuple[str, str]:
    """-> (markdown, csv). Same inputs + same registry version => identical bytes."""
    transfers = scanned["transfers"]

    buf = io.StringIO()
    writer = csv.writer(buf, lineterminator="\n")
    writer.writerow(["timestamp", "tx_hash", "recipient", "service_id", "service_name",
                     "category", "amount_usdc", "direction"])
    for t in transfers:
        svc = t["service"] or {}
        writer.writerow([
            _iso(t["ts"]), t["tx_hash"], t["counterparty"],
            svc.get("service_id") or "", svc.get("name") or "",
            t["category"], _usdc6(t["atomic"]), t["direction"],
        ])
    csv_text = buf.getvalue()
    csv_sha = hashlib.sha256(csv_text.encode()).hexdigest()

    tot = summary["totals"]
    top = summary["groups"][:5]
    lines = [
        f"# {title or 'x402 spend report — ' + summary['wallet']}",
        "",
        f"- **Wallet:** `{summary['wallet']}`",
        "- **Chain:** Base (eip155:8453), USDC",
        f"- **Range:** {summary['range']['from']} → {summary['range']['to']} ({summary['direction']})",
        f"- **Registry version:** {summary['registry_version']} · spec {SPEC_VERSION}",
    ]
    if prepared_for:
        lines.append(f"- **Prepared for:** {prepared_for}")
    lines += [
        f"- **CSV SHA-256:** `{csv_sha}`",
        "",
        "## Summary",
        "",
        f"Total: **{tot['usdc']} USDC** across **{tot['tx_count']} transactions** to "
        f"**{tot['unique_recipients']} recipients** — {tot['identified_pct']}% of volume "
        "matched to a known service.",
        "",
        "| # | Service | USDC | Txs |",
        "|---|---------|------|-----|",
    ]
    lines += [
        f"| {i + 1} | {g['label']} | {g['usdc']} | {g['tx_count']} |"
        for i, g in enumerate(top)
    ]
    lines += [
        "",
        "## Per-service breakdown",
        "",
        "| Service | Category | Recipient | Txs | Total USDC | Avg price | First | Last |",
        "|---------|----------|-----------|-----|-----------|-----------|-------|------|",
    ]
    for g in summary["groups"]:
        cat = ""
        if g["service_id"]:
            svc = registry()["recipients"].get(g["recipient"]) or {}
            cat = svc.get("category") or ""
        lines.append(
            f"| {g['label']} | {cat} | `{g['recipient']}` | {g['tx_count']} "
            f"| {g['usdc']} | {g['avg_call_price']} | {g['first_tx'][:10]} | {g['last_tx'][:10]} |"
        )
    unit = "Week of" if summary["granularity"] == "week" else "Date"
    lines += [
        "",
        f"## {'Weekly' if summary['granularity'] == 'week' else 'Daily'} spend",
        "",
        f"| {unit} | USDC | Txs |",
        "|------|------|-----|",
    ]
    lines += [f"| {d['date']} | {d['usdc']} | {d['tx_count']} |" for d in summary["daily"]]
    lines += ["", _METHODOLOGY.format(registry_version=summary["registry_version"])]
    return "\n".join(lines), csv_text


# --- async report job (runs in the same Lambda via self-invoke) ---------------

REPORTS_BUCKET = os.getenv("LEDGER_REPORTS_BUCKET", "")
PUBLIC_BASE = os.getenv("PUBLIC_BASE_URL", "https://api.anchor-x402.com")


def run_report_job(event: dict[str, Any]) -> dict[str, Any]:
    """Worker path: scan -> render -> sign -> anchor -> S3 -> DDB. Invoked
    async by the dispatch route; failures mark the job FAILED so the
    existing refund machinery (poll / push / cron) repays the buyer."""
    import boto3

    job_id = event["job_id"]
    p = event["params"]
    table = boto3.resource("dynamodb").Table(os.environ.get("INVESTIGATOR_JOBS_TABLE", "risk-investigator-jobs"))

    def set_status(status: str, **fields: Any) -> None:
        expr = "SET #s = :s, updated_at = :u" + "".join(f", {k} = :{k}" for k in fields)
        values: dict[str, Any] = {":s": status, ":u": int(time.time())}
        values.update({f":{k}": v for k, v in fields.items()})
        table.update_item(
            Key={"job_id": job_id},
            UpdateExpression=expr,
            ExpressionAttributeNames={"#s": "status"},
            ExpressionAttributeValues=values,
        )

    try:
        set_status("IN_PROGRESS")
        scanned = scan(
            p["wallet"], p["from_ts"], p["to_ts"], p["direction"],
            p.get("min_amount"), p.get("include_unfiltered", False),
        )
        summary = summarize(scanned, p["wallet"], p["from_ts"], p["to_ts"],
                            p["direction"], p.get("group_by", "service"))
        md, csv_text = render_report(scanned, summary, p.get("title"), p.get("prepared_for"))
        md_sha = hashlib.sha256(md.encode()).hexdigest()

        from eth_account import Account
        from eth_account.messages import encode_defunct
        from services import anchor as anchor_svc
        from services import secrets

        key = secrets.get("treasury_evm_key", env_fallback="TREASURY_PRIVATE_KEY")
        acct = Account.from_key(key)
        signed = acct.sign_message(encode_defunct(
            f"anchor-x402/ledger/v1\nsha256={md_sha}".encode()
        ))
        sig_hex = signed.signature.hex()
        if not sig_hex.startswith("0x"):
            sig_hex = "0x" + sig_hex

        anchored = anchor_svc.anchor_dual_chain(md_sha)

        s3 = boto3.client("s3")
        fmt = p.get("format", "both")
        deliverable: dict[str, Any] = {
            "report_sha256": md_sha,
            "signature": {"signer": acct.address, "scheme": "eip191",
                          "domain": "anchor-x402/ledger/v1", "value": sig_hex},
            "anchor": {
                "base_tx": f"https://basescan.org/tx/{anchored['base_tx']}",
                "solana_tx": f"https://solscan.io/tx/{anchored['solana_tx']}" if anchored.get("solana_tx") else None,
            },
            "registry_version": summary["registry_version"],
            "spec_version": SPEC_VERSION,
        }
        if fmt in ("markdown", "both"):
            s3.put_object(Bucket=REPORTS_BUCKET, Key=f"ledger/{job_id}.md",
                          Body=md.encode(), ContentType="text/markdown; charset=utf-8")
            deliverable["report_markdown_url"] = f"{PUBLIC_BASE}/reports/ledger/{job_id}.md"
        if fmt in ("csv", "both"):
            s3.put_object(Bucket=REPORTS_BUCKET, Key=f"ledger/{job_id}.csv",
                          Body=csv_text.encode(), ContentType="text/csv; charset=utf-8")
            deliverable["report_csv_url"] = f"{PUBLIC_BASE}/reports/ledger/{job_id}.csv"

        set_status("DELIVERED", deliverable=deliverable)
        return {"job_id": job_id, "status": "DELIVERED"}
    except LedgerError as e:
        log.warning("ledger job %s failed: %s %s", job_id, e.code, e.message)
        set_status("FAILED", error_msg=f"{e.code}: {e.message}")
        return {"job_id": job_id, "status": "FAILED"}
    except Exception as e:  # noqa: BLE001
        log.exception("ledger job %s crashed", job_id)
        set_status("FAILED", error_msg=f"{type(e).__name__}: {e}")
        return {"job_id": job_id, "status": "FAILED"}
