#!/usr/bin/env python3
"""Project the request models into docs/.well-known/x402.json `input_schema`.

These blocks used to be hand-authored next to the catalog copy. They drifted:
the models enforce constraints the catalog never mentioned (`/v1/tldr` text
maxLength 200000, `/v1/oracle` question minLength 1), so a client obeying the
catalog could send a body the server rejects with 422. An external reconciler
diffed the catalog against /openapi.json and could not derive one from the
other, which is the correct conclusion — they were two independent hand-offs
from one contract.

/openapi.json is generated by FastAPI from the same Pydantic models the server
validates against, so it is authoritative. This projects those models into the
catalog's flavour of JSON Schema:

  * inline $refs                    (the catalog is read standalone, no components)
  * drop Pydantic's generated title (noise; the property name already says it)
  * unwrap Optional[T]              (anyOf [T, null] -> T)
  * integral floats -> ints         (maximum: 100.0 -> 100)

Query-parameter routes have no request body, so their schema is assembled from
the declared query parameters into the same object shape. Those four also keep
their older `params` block: it is non-standard but published, and removing a
field from a public catalog breaks consumers we cannot see.

  .venv/bin/python scripts/gen_x402_schemas.py            # rewrite in place
  .venv/bin/python scripts/gen_x402_schemas.py --check    # non-zero if stale
"""
from __future__ import annotations

import argparse
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

CATALOG_PATH = os.path.join(ROOT, "docs", ".well-known", "x402.json")

# Keywords worth carrying into the catalog. Everything else Pydantic emits is
# either presentation (title) or machinery the catalog has no use for.
_KEEP = {
    "type", "description", "default", "enum", "const", "format",
    "minimum", "maximum", "exclusiveMinimum", "exclusiveMaximum",
    "minLength", "maxLength", "pattern", "minItems", "maxItems",
    "properties", "required", "items", "additionalProperties", "anyOf",
}
_NUMERIC = {"minimum", "maximum", "exclusiveMinimum", "exclusiveMaximum",
            "minLength", "maxLength", "minItems", "maxItems"}


def _unfiltered_openapi() -> dict:
    """FastAPI's own schema, before app.py strips the GET/POST wrapper twins.
    The twins are hidden from the published spec, but the catalog documents
    whichever method it declares, so generation needs every operation."""
    from fastapi.openapi.utils import get_openapi

    import app as app_module

    return get_openapi(
        title=app_module.app.title,
        version=app_module.app.version,
        routes=app_module.app.routes,
    )


def _resolve(node, components, depth=0):
    """Inline $refs so the catalog stays a standalone document."""
    if depth > 8:
        return node
    if isinstance(node, list):
        return [_resolve(i, components, depth + 1) for i in node]
    if not isinstance(node, dict):
        return node
    if "$ref" in node:
        name = node["$ref"].rsplit("/", 1)[-1]
        return _resolve(components.get(name, {}), components, depth + 1)
    return {k: _resolve(v, components, depth + 1) for k, v in node.items()}


def _project(node):
    """Pydantic's JSON Schema -> the catalog's flavour of it."""
    if isinstance(node, list):
        return [_project(i) for i in node]
    if not isinstance(node, dict):
        return node

    # Optional[T] renders as anyOf [T, null]. The catalog states the bare type
    # and marks optionality by absence from `required`, so collapse it.
    if "anyOf" in node:
        branches = [b for b in node["anyOf"] if b != {"type": "null"}]
        if len(branches) == 1 and len(branches) == len(node["anyOf"]) - 1:
            merged = dict(branches[0])
            for key, value in node.items():
                if key not in ("anyOf", "title"):
                    merged.setdefault(key, value)
            return _project(merged)

    out = {}
    for key, value in node.items():
        if key not in _KEEP:
            continue
        if key in _NUMERIC and isinstance(value, float) and value.is_integer():
            out[key] = int(value)
        elif key == "properties":
            out[key] = {k: _project(v) for k, v in value.items()}
        else:
            out[key] = _project(value)
    return out


def _body_schema(operation, components):
    content = (operation.get("requestBody") or {}).get("content", {})
    schema = (content.get("application/json") or {}).get("schema")
    return _project(_resolve(schema, components)) if schema else None


def _query_schema(operation, components):
    """Assemble declared query parameters into the same object shape a body
    route publishes, so all 18 routes speak one schema family."""
    properties, required = {}, []
    for param in operation.get("parameters") or []:
        if param.get("in") != "query":
            continue
        prop = _project(_resolve(param.get("schema") or {}, components))
        # FastAPI puts the description on the parameter, not always its schema.
        if param.get("description") and "description" not in prop:
            prop["description"] = param["description"]
        properties[param["name"]] = prop
        if param.get("required"):
            required.append(param["name"])
    if not properties:
        return None
    schema = {"type": "object", "properties": properties}
    if required:
        schema["required"] = required
    return schema


def build() -> dict:
    spec = _unfiltered_openapi()
    components = spec.get("components", {}).get("schemas", {})
    with open(CATALOG_PATH, encoding="utf-8") as handle:
        catalog = json.load(handle)

    missing = []
    for route in catalog.get("routes", []):
        path, method = route["path"], route["method"].lower()
        operation = (spec.get("paths", {}).get(path) or {}).get(method)
        if not operation:
            missing.append(f"{route['method']} {path}")
            continue
        schema = _body_schema(operation, components) or _query_schema(operation, components)
        if schema is None:
            missing.append(f"{route['method']} {path} (no body or query schema)")
            continue
        route["input_schema"] = schema

    if missing:
        raise SystemExit("catalog routes with no matching operation: " + ", ".join(missing))
    return catalog


def serialize(catalog: dict) -> str:
    # Byte-identical to how the catalog is already written.
    return json.dumps(catalog, indent=2, ensure_ascii=False) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the catalog is stale instead of rewriting it")
    args = parser.parse_args()

    rendered = serialize(build())
    with open(CATALOG_PATH, encoding="utf-8") as handle:
        current = handle.read()

    if rendered == current:
        print("x402.json input_schema up to date")
        return
    if args.check:
        raise SystemExit("x402.json input_schema is stale — run scripts/gen_x402_schemas.py")
    with open(CATALOG_PATH, "w", encoding="utf-8") as handle:
        handle.write(rendered)
    print(f"wrote {CATALOG_PATH} ({len(rendered.encode())} bytes)")


if __name__ == "__main__":
    main()
